appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jIT2qTuRaRvCxHQzwAbdFC7pFLE+PdnhkYowJCnYMpiUTTxUfMJCWU1K595H4VWhJzok39bMjIISGkdD3PsRDHsI0cB8plvQdD1L97uYgPImZideK6pjPO1Gv9cbe8vn0QYUJss+Tb4eumQmJvKu1VjUx2fgL3FVX8X4Ju31upAH4YtXQuO6p9d91xeQ/Ui6eHuSUrfDmaGhlomL2vZA88mJikF/PTvT0MdBq3jsiMYaXNvXuWAHKDMqkHl7GxJlZER4wAPxH6JDJZIjCWNmFdEjXvUanizxQmlrKmDLSW3Ri0mu6Bgkb+oOMral6S80TPXZ92dx6iDtT4kt8/HBg7BhXKBtOwI2BIprNnAVOyV3qw+KohSc2hKUJeJqwYaAuDjWplWEtoyPd73Apujo/a+76GXtjEPbmILB3XE0qQkyhZwGBHNesdwiwPfpU7L1tFDG7y+96qsLbz0OqY3YnBm60S4YMn/Gh74MuZHD7ofDSbcOvXYlFUzGjZ/Ojp5AaOPDRocgWWRcOk6QRoCg8ZZLTZNmX5e48aMkNh/CcBwmqvhcJDbjTtO4MCwrVDDFjqEvoUwhE/aATBfB3wSTVIBKtHe/oJ+Ewzxcdqi6uyvJjPBCzVzfBTRcnDRE9oqV4VrVMzzFcjbUqwEi8TdouU8A3grSY7VbrmUbBsJbq1s=}
